#!/bin/bash

source $(pwd)/config

if [[ -z $PHYSICAL_BOOT ]];then
    echo "Error disk boot is empty" && exit
fi

if [[ -z $PHYSICAL_PROC ]];then
    echo "Error disk proc is empty" && exit
fi

if [[ -z $PHYSICAL_DATA ]];then
    echo "Error disk data is empty" && exit
fi

if [[ -z $DESK_USERNAME ]];then
    echo "Error username data is empty" && exit
fi


if [[ -e /dev/mapper/proc ]];then
    cryptsetup luksFormat --sector-size=4096 $PHYSICAL_PROC &&
    cryptsetup luksOpen $PHYSICAL_PROC proc &&
    echo "encrypted proc volume"
fi


if [[ -e /dev/mapper/data ]];then
    cryptsetup luksFormat --sector-size=4096 $PHYSICAL_DATA &&
    cryptsetup luksOpen $PHYSICAL_DATA data &&
    echo "encrypted data volume"
fi


sleep 3 && clear &&
echo "level 2" &&
echo "create volume group proc" &&
if [[ -z $(vgs | grep proc ) ]];then
    pvcreate /dev/mapper/proc  && vgcreate proc /dev/mapper/proc
fi


sleep 3 && clear &&
echo "level 3" &&
if [[ ! -e /dev/proc/root ]];then
    lvcreate -L 10G proc -n root
fi
yes Y | mkfs.ext4 -b 4096 /dev/proc/root &&
mount /dev/proc/root /mnt &&



sleep 3 && clear &&
echo "level 4" &&
if [[ ! -e /mnt/boot ]];then
    echo "Error boot partition not found"
    exit
fi
yes Y | mkfs.vfat -F32 -S 4096 -n BOOT $PHYSICAL_BOOT &&
mkdir /mnt/boot &&
mount -o uid=0,gid=0,fmask=0077,dmask=0077 $PHYSICAL_BOOT /mnt/boot &&


sleep 3 && clear &&
echo "level 5" &&
if [[ ! -e /dev/proc/opts ]];then
    lvcreate -L 15G proc -n opts
fi
yes Y | mkfs.ext4 -b 4096 /dev/proc/opts &&
mkdir /mnt/opt &&
mount -o rw,nodev,nosuid,relatime /dev/proc/opts /mnt/opt &&


sleep 3 && clear &&
echo "level 6" &&
if [[ ! -e /dev/proc/vars ]];then
   lvcreate -L 2G proc -n vars
fi
yes Y | mkfs.ext4 -b 4096 /dev/proc/vars &&
mkdir /mnt/var &&
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/vars /mnt/var &&


sleep 3 && clear &&
echo "level 7" 
if [[ ! -e /dev/proc/libs ]];then
    lvcreate -L 512M proc -n libs
fi
yes Y | mkfs.ext4 -b 4096 /dev/proc/libs &&
mkdir /mnt/var/usr &&
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/libs /mnt/var/usr &&


sleep 3 && clear &&
echo "level 8" &&
if [[ ! -e /dev/proc/game ]];then
    lvcreate -L 512M proc -n game
fi
yes Y | mkfs.ext4 -b 4096 /dev/proc/game &&
mkdir /mnt/var/games &&
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/game /mnt/var/games &&


sleep 3 && clear &&
echo "level 9" &&
if [[ ! -e /dev/proc/vlog ]];then
    lvcreate -L 1G proc -n vlog
fi
yes Y | mkfs.ext4 -b 4096 /dev/proc/vlog &&
mkdir /mnt/var/log &&
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/vlog /mnt/var/log &&


sleep 3 &&
clear &&
echo "level 10" &&
if [[ ! -e /dev/proc/vaud ]];then
    lvcreate -L 256M proc -n vaud
fi
yes Y | mkfs.ext4 -b 4096 /dev/proc/vaud &&
mkdir /mnt/var/log/audit &&
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/vaud /mnt/var/log/audit


sleep 3 &&
clear &&
echo "level 11" &&
if [[ ! -e /dev/proc/vtmp ]];then
    lvcreate -L 2G proc -n vtmp
fi
yes Y | mkfs.ext4 -b 4096 /dev/proc/vtmp &&
mkdir /mnt/var/tmp &&
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/vtmp /mnt/var/tmp &&


sleep 3 && clear &&
echo "level 12" &&
if [[ ! -e /dev/proc/vpac ]];then
    lvcreate -L 2G proc -n vpac
fi
yes Y | mkfs.ext4 -b 4096 /dev/proc/vpac &&
mkdir -p /mnt/var/cache/pacman &&
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/vpac /mnt/var/cache/pacman &&


sleep 3 && clear &&
echo "level 13" &&
if [[ ! -e /dev/proc/ring ]];then
    lvcreate -L 512M proc -n ring
fi
cryptsetup luksFormat --sector-size=4096 /dev/proc/ring &&
cryptsetup luksOpen /dev/proc/ring lvm_keys &&
mkfs.ext4 -b 4096 /dev/mapper/lvm_keys


sleep 3 && clear &&
echo "level 14" &&
if [[ ! -e /dev/proc/docs ]];then
    lvcreate -l100%FREE proc -n docs
fi
mkfs.ext4 -b 4096 /dev/proc/docs &&
mkdir -p /mnt/srv /mnt/srv/http &&
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/docs /mnt/srv/http &&


## network
sleep 3 && clear &&
echo "level 15" &&
pacstrap /mnt openssh ethtool iptables-nft firewalld --noconfirm  &&
cp /etc/system/network/* /mnt/etc/systemd/network/  &&

if [[ ! -z $( ip a | grep "wl*" )  ]];then
    mkdir -p /mnt/var/lib/iwd/ &&
    pacstrap /mnt iwd --noconfirm &&
    cp /var/lib/iwd/* /mnt/var/lib/iwd/
fi


## kernel
sleep 3 && clear &&
echo "level 16" &&
pacstrap /mnt linux-hardened linux-firmware mkinitcpio base lvm2 btrfs-progs bubblewrap-suid --noconfirm &&


## devel
sleep 3 && clear &&
echo "level 17" &&
pacstrap /mnt sudo debugedit fakeroot pkgconf bison gcc pcre flex wget make gcc curl less git --noconfirm &&


## audio
sleep 3 && clear &&
echo "level 18" &&
pacstrap /mnt pipewire pipewire-pulse pipewire-jack wireplumber pavucontrol sof-firmware mpd mpc --noconfirm &&


## graphic
sleep 3 && clear &&
echo "level 19" &&
pacstrap /mnt brightnessctl xorg-xwayland --noconfirm &&


## fontsys
sleep 3 && clear &&
echo "level 20" &&
pacstrap /mnt ttf-jetbrains-mono-nerd ttf-droid --noconfirm &&

## desktop
sleep 3 && clear &&
echo "level 21" &&
pacstrap /mnt sddm uwsm hyprland hyprpicker hyprshot hypridle hyprlock hyprpolkitagent xdg-desktop-portal-hyprland qt5-wayland qt6-wayland wl-clipboard cliphist mailcap --noconfirm &&


## panelis
sleep 3 && clear &&
echo "level 22" &&
pacstrap /mnt mako waybar wofi --noconfirm &&


## fileman
sleep 3 && clear &&
echo "level 23" &&
pacstrap /mnt nautilus nautilus-image-converter sushi --noconfirm &&


## terminal
sleep 3 && clear &&
echo "level 24" &&
pacstrap /mnt kitty kitty-terminfo neovim --noconfirm &&


## password
sleep 3 && clear &&
echo "level 25" &&
pacstrap /mnt gnome-keyring libsecret libpam-google-authenticator libpwquality cracklib polkit apparmor qrencode --noconfirm &&


## monitoring
sleep 3 && clear &&
echo "level 26" &&
pacstrap /mnt prometheus prometheus-node-exporter btop --noconfirm &&


## performance
sleep 3 && clear && 
echo "level 27" &&
pacstrap /mnt irqbalance tuned tuned-ppd --noconfirm &&


## backup
sleep 3 && clear &&
echo "level 28" &&
pacstrap /mnt rsync grsync --noconfirm &&


## hosting
sleep 3 && clear &&
echo "level 29" &&
pacstrap /mnt go hugo nginx --noconfirm &&


## ucode
sleep 3 && clear &&
echo "level 30" &&
if [[ ! -z $( cat /proc/cpuinfo | grep "Intel" )  ]];then
    pacstrap /mnt intel-ucode --noconfirm
fi
if [[ ! -z $( cat /proc/cpuinfo | grep "AMD" )  ]];then
    pacstrap /mnt amd-ucode --noconfirm
fi


## ndbe
sleep 3 && clear &&
echo "level 31" &&
pacstrap /mnt tang clevis mkinitcpio-nfs-utils luksmeta &&


sleep 3 && clear &&
echo "level 32" &&
echo "copy post installation script"
cp -fr post  /mnt/ &&


sleep 3 && clear &&
echo "level 33" &&
echo "copy post installation script" &&
if [[ ! -e  /mnt/opt/ ]];then
    echo "Error /mnt/opt doesnt exist, installation failed" 
    exit
fi

git clone https://github.com/blackbird-package/level20.git /mnt/opt/config &&
echo "base configuration done" &&
cp -fr /mnt/opt/config/base/* /mnt &&
echo "udev configuration done" &&
cp -fr /mnt/opt/config/udev/* /mnt &&
cp $(pwd)/config /mnt/post &&


sleep 3 && clear &&
echo "level 34" &&
genfstab -U /mnt > /mnt/etc/fstab &&
echo "" >> /mnt/etc/fstab &&
echo "# /dev/mapper/proc-temp" >> /mnt/etc/fstab &&
echo "tmpfs     					/tmp        		tmpfs   defaults,rw,nosuid,nodev,noexec,relatime,size=256M" >>  /mnt/etc/fstab &&


sleep 3 && clear &&
echo "level 35" &&
arch-chroot /mnt /bin/bash /post/udvtang-post-install