#!/bin/bash

source $(pwd)/config

if [[ -z $PHYSICAL_BOOT ]];then
    echo "Error disk boot is empty" &&
    exit
fi

if [[ -z $PHYSICAL_PROC ]];then
    echo "Error disk proc is empty" &&
    exit
fi

if [[ -z $PHYSICAL_DATA ]];then
    echo "Error disk data is empty" &&
    exit
fi


if [[ -z $DESK_USERNAME ]];then
    echo "Error username data is empty" &&
    exit
fi

cryptsetup luksFormat --sector-size=4096 $PHYSICAL_PROC &&
cryptsetup luksOpen $PHYSICAL_PROC proc &&

if [[ -z /dev/mapper/proc ]];then
    echo "Error proc partition not found" &&
    exit
fi


cryptsetup luksFormat --sector-size=4096 $PHYSICAL_DATA &&
cryptsetup luksOpen $PHYSICAL_DATA data &&

if [[ -z /dev/mapper/data ]];then
    echo "Error data partition not found" &&
    exit
fi


sleep 1 && clear &&
echo "level 2" &&
pvcreate /dev/mapper/proc  &&
vgcreate proc /dev/mapper/proc &&


sleep 1 && clear &&
echo "level 3" &&
lvcreate -L 10G proc -n root &&
mkfs.ext4 -b 4096 /dev/proc/root &&
mount /dev/proc/root /mnt &&

if [[ -z /dev/proc/root ]];then
    echo "Error root partition not found" &&
    exit
fi


sleep 1 && clear &&
echo "level 4" &&
yes Y | mkfs.vfat -F32 -S 4096 -n BOOT $PHYSICAL_BOOT &&
mkdir /mnt/boot &&
mount -o uid=0,gid=0,fmask=0077,dmask=0077 $PHYSICAL_BOOT /mnt/boot &&

if [[ -z /mnt/boot ]];then
    echo "Error boot partition not found" &&
    exit
fi

sleep 1 && clear &&
echo "level 5" &&
lvcreate -L 15G proc -n opts &&
yes Y | mkfs.ext4 -b 4096 /dev/proc/opts &&
mkdir /mnt/opt &&
mount -o rw,nodev,nosuid,relatime /dev/proc/opts /mnt/opt &&

if [[ -z /dev/proc/opts ]];then
    echo "Error boot partition not found" &&
    exit
fi


sleep 1 && clear &&
echo "level 6" &&
lvcreate -L 2G proc -n vars &&
yes Y | mkfs.ext4 -b 4096 /dev/proc/vars &&
mkdir /mnt/var &&
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/vars /mnt/var &&

if [[ -z /dev/proc/vars ]];then
    echo "Error boot partition not found" &&
    exit
fi


sleep 1 && clear &&
echo "level 7" 
lvcreate -L 512M proc -n libs &&
yes Y | mkfs.ext4 -b 4096 /dev/proc/libs &&
mkdir /mnt/var/usr &&
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/libs /mnt/var/usr &&

if [[ -z /dev/proc/libs ]];then
    echo "Error boot partition not found" &&
    exit
fi


sleep 1 && clear &&
echo "level 8" &&
lvcreate -L 512M proc -n game &&
yes Y | mkfs.ext4 -b 4096 /dev/proc/game &&
mkdir /mnt/var/games &&
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/game /mnt/var/games &&

if [[ -z /dev/proc/game ]];then
    echo "Error boot partition not found" &&
    exit
fi


sleep 1 && clear &&
echo "level 9" &&
lvcreate -L 1G proc -n vlog &&
yes Y | mkfs.ext4 -b 4096 /dev/proc/vlog &&
mkdir /mnt/var/log &&
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/vlog /mnt/var/log &&

if [[ -z /dev/proc/vlog ]];then
    echo "Error boot partition not found" &&
    exit
fi


sleep 1 &&
clear &&
echo "level 10" &&
lvcreate -L 256M proc -n vaud &&
yes Y | mkfs.ext4 -b 4096 /dev/proc/vaud &&
mkdir /mnt/var/log/audit &&
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/vaud /mnt/var/log/audit &&

if [[ -z /dev/proc/vaud ]];then
    echo "Error boot partition not found" &&
    exit
fi


sleep 1 &&
clear &&
echo "level 11" &&
lvcreate -L 2G proc -n vtmp &&
yes Y | mkfs.ext4 -b 4096 /dev/proc/vtmp &&
mkdir /mnt/var/tmp &&
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/vtmp /mnt/var/tmp &&

if [[ -z /dev/proc/vtmp ]];then
    echo "Error boot partition not found" &&
    exit
fi


sleep 1 && clear &&
echo "level 12" &&
lvcreate -L 2G proc -n vpac &&
yes Y | mkfs.ext4 -b 4096 /dev/proc/vpac &&
mkdir -p /mnt/var/cache/pacman &&
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/vpac /mnt/var/cache/pacman &&

if [[ -z /dev/proc/vpac ]];then
    echo "Error boot partition not found" &&
    exit
fi


sleep 1 && clear &&
echo "level 13" &&
lvcreate -L 512M proc -n ring &&
cryptsetup luksFormat --sector-size=4096 /dev/proc/ring &&
cryptsetup luksOpen /dev/proc/ring lvm_keys &&

if [[ -z /dev/proc/ring ]];then
    echo "Error boot partition not found" 
    exit
else
    mkfs.ext4 -b 4096 /dev/mapper/lvm_keys
fi


sleep 1 && clear &&
echo "level 14" &&
lvcreate -l100%FREE proc -n docs &&
mkfs.ext4 -b 4096 /dev/proc/docs &&
mkdir -p /mnt/srv /mnt/srv/http &&
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/docs /mnt/srv/http &&

if [[ -z /dev/proc/docs ]];then
    echo "Error boot partition not found" &&
    exit
fi


## network
sleep 1 && clear &&
echo "level 15" &&
pacstrap /mnt openssh ethtool iptables-nft firewalld --noconfirm  &&
cp /etc/system/network/* /mnt/etc/systemd/network/  &&

if [[ ! -z $( ip a | grep "wl*" )  ]];then
    mkdir -p /mnt/var/lib/iwd/ &&
    pacstrap /mnt iwd --noconfirm &&
    cp /var/lib/iwd/* /mnt/var/lib/iwd/
fi


## kernel
sleep 1 && clear &&
echo "level 16" &&
pacstrap /mnt linux-hardened linux-firmware mkinitcpio base lvm2 btrfs-progs bubblewrap-suid --noconfirm &&


## devel
sleep 1 && clear &&
echo "level 17" &&
pacstrap /mnt sudo debugedit fakeroot pkgconf bison gcc pcre flex wget make gcc curl less git --noconfirm &&


## audio
sleep 1 && clear &&
echo "level 18" &&
pacstrap /mnt pipewire pipewire-pulse pipewire-jack wireplumber pavucontrol sof-firmware mpd mpc --noconfirm &&


## graphic
sleep 1 && clear &&
echo "level 19" &&
pacstrap /mnt brightnessctl xorg-xwayland --noconfirm &&


## fontsys
sleep 1 && clear &&
echo "level 20" &&
pacstrap /mnt ttf-jetbrains-mono-nerd ttf-droid --noconfirm &&

## desktop
sleep 1 && clear &&
echo "level 21" &&
pacstrap /mnt sddm uwsm hyprland hyprpicker hyprshot hypridle hyprlock hyprpolkitagent xdg-desktop-portal-hyprland qt5-wayland qt6-wayland wl-clipboard cliphist mailcap --noconfirm &&


## panelis
sleep 1 && clear &&
echo "level 22" &&
pacstrap /mnt mako waybar wofi --noconfirm &&


## fileman
sleep 1 && clear &&
echo "level 23" &&
pacstrap /mnt nautilus nautilus-image-converter sushi --noconfirm &&


## terminal
sleep 1 && clear &&
echo "level 24" &&
pacstrap /mnt kitty kitty-terminfo neovim --noconfirm &&


## password
sleep 1 && clear &&
echo "level 25" &&
pacstrap /mnt gnome-keyring libsecret libpam-google-authenticator libpwquality cracklib polkit apparmor qrencode --noconfirm &&


## monitoring
sleep 1 && clear &&
echo "level 26" &&
pacstrap /mnt prometheus prometheus-node-exporter btop --noconfirm &&


## performance
sleep 1 && clear && 
echo "level 27" &&
pacstrap /mnt irqbalance tuned tuned-ppd --noconfirm &&


## backup
sleep 1 && clear &&
echo "level 28" &&
pacstrap /mnt rsync grsync --noconfirm &&


## hosting
sleep 1 && clear &&
echo "level 29" &&
pacstrap /mnt go hugo nginx --noconfirm &&


## ucode
sleep 1 && clear &&
echo "level 30" &&
if [[ ! -z $( cat /proc/cpuinfo | grep "Intel" )  ]];then
    pacstrap /mnt intel-ucode --noconfirm
fi
if [[ ! -z $( cat /proc/cpuinfo | grep "AMD" )  ]];then
    pacstrap /mnt amd-ucode --noconfirm
fi


## ndbe
sleep 1 && clear &&
echo "level 31" &&
pacstrap /mnt tang clevis mkinitcpio-nfs-utils luksmeta &&


sleep 1 && clear &&
echo "level 32" &&
echo "copy post installation script"
cp -fr post  /mnt/ &&


sleep 1 && clear &&
echo "level 33" &&
echo "copy post installation script" &&
git clone https://github.com/blackbird-package/level20.git /mnt/opt/config &&
echo "base configuration done" &&
cp -fr /mnt/opt/config/base/* /mnt &&
echo "udev configuration done" &&
cp -fr /mnt/opt/config/udev/* /mnt &&
cp $(pwd)/config /mnt/post &&


sleep 1 && clear &&
echo "level 34" &&
genfstab -U /mnt > /mnt/etc/fstab &&
echo "" >> /mnt/etc/fstab &&
echo "# /dev/mapper/proc-temp" >> /mnt/etc/fstab &&
echo "tmpfs     					/tmp        		tmpfs   defaults,rw,nosuid,nodev,noexec,relatime,size=256M" >>  /mnt/etc/fstab &&


sleep 1 && clear &&
echo "level 35" &&
arch-chroot /mnt /bin/bash /post/udvtang-post-install