#!/bin/bash

source /post/config
shadow='$6$xyz$TcdM.glK/cahP/.4LRfB6cLr9mczMfZazDDq4Bou89AbP36r/UXNQ6TIxuCpM3hZ9V5QKTSo6954a.1DM3k7E0'

if [[ -z $PHYSICAL_BOOT ]];then
    echo "Error disk boot is empty" &&
    exit
fi

if [[ -z $PHYSICAL_PROC ]];then
    echo "Error disk proc is empty" &&
    exit
fi

if [[ -z $PHYSICAL_PROC ]];then
    echo "Error disk data is empty" &&
    exit
fi

if [[ -z $DESK_HOSTNAME ]];then
    echo "Error hostname data is empty" &&
    exit
fi

if [[ -z $IP_ADDRESSING ]];then
    echo "Error ip address data is empty" &&
    exit
fi

if [[ -z $IP_ADDRESSING ]];then
    echo "Error ip address data is empty" &&
    exit
fi

if [[ -z $DESK_USERNAME ]];then
    echo "Error username data is empty" &&
    exit
fi


## hostname
sleep 3 && clear &&
echo "level 1" &&
mkdir /usr/local/rbin &&
echo $DESK_HOSTNAME > /etc/hostname


## timectl
sleep 3 && clear &&
echo "level 2"
ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime &&
hwclock --systohc &&
timedatectl set-ntp true &&
timedatectl set-timezone Asia/Jakarta &&
timedatectl status &&
timedatectl show-timesync --all &&
systemctl enable systemd-timesyncd.service &&


## locale
sleep 3 && clear &&
echo "level 3"
locale-gen  &&


## administrator
sleep 3 && clear &&
echo "level 4" &&
if [ -e /etc/skel/.bashrc ];then
    rm /etc/skel/.bash*
fi
if [[ -z $( grep loki /etc/passwd ) ]];then
    useradd -d /var/usr -p $shadow loki &&
    chown -R loki:loki /var/usr &&
    chmod 700 /var/usr/.ssh/ &&
    chmod 600 /var/usr/.ssh/authorized_keys &&
    sudo chattr +i /var/usr/.ssh/authorized_keys &&
    usermod -aG wheel loki
fi






 
## virtualmin
sleep 3 && clear &&
echo "level 5" &&
if [[ -z $( grep games /etc/passwd ) ]];then
    useradd -d /var/games -u 50 -g games games &&
    chown -R games:games /var/games &&
    passwd -l games
fi



## useradd
sleep 3 && clear &&
echo "level 6" &&
touch /etc/sudoers.d/none &&

if [[ -z $( grep $DESK_USERNAME /etc/passwd ) ]];then
    useradd -m $DESK_USERNAME
fi
passwd $DESK_USERNAME &&
echo "$DESK_USERNAME ALL=(ALL:ALL) ALL" > /etc/sudoers.d/none &&


## application
sleep 3 && clear &&
echo "level 7"&&
mkdir -p /opt/flat &&
ln -sf /opt/flat /var/lib/flatpak &&
pacman /mnt flatpak gnome-software --noconfirm &&



## aide hids
sleep 3 && clear &&
echo "level 8" &&
pkg-config --libs --cflags glib-2.0 &&
cd /tmp &&
wget https://github.com/aide/aide/releases/download/v0.19.2/aide-0.19.2.tar.gz  &&
sudo tar -xf aide-0.19.2.tar.gz &&
cd aide-0.19.2 &&
sudo ./configure --with-zlib --with-posix-acl --with-xattr --with-curl --with-locale --with-syslog-ident --with-config-file=/etc/aide.conf &&
sudo make && make install &&
mkdir -p /var/lib/aide &&


## clevis
sleep 3 && clear &&
echo "level 9" &&

echo "games ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/game &&
sudo -H -u games /bin/bash -c "git clone https://aur.archlinux.org/yay /tmp/clevis-hook" &&
sudo -H -u games /bin/bash -c "makepkg -sric --dir /tmp/yay --noconfirm"
sudo -H -u games /bin/bash -c "rm -fr /tmp/clevis-hook"
echo "games ALL=(ALL:ALL) ALL" > /etc/sudoers.d/game &&


## params conf
sleep 3 && clear &&
echo "level 10" &&
echo "cryptdevice=UUID=$(blkid -s UUID -o value $PHYSICAL_PROC):proc root=/dev/proc/root" > /etc/cmdline.d/01-boot.conf &&
echo "data UUID=$(blkid -s UUID -o value $PHYSICAL_DATA) none" >> /etc/crypttab &&



## nbde server
sleep 3 && clear &&
echo "level 11" &&
echo "ip=$IP_ADDRESSING::10.10.1.1:255.255.255.0::eth0:none nameserver=10.10.1.1 nameserver=1.1.1.1 nameserver=8.8.8.8 nameserver=1.0.0.1 nameserver=8.8.4.4 nameserver=9.9.9.9 nameserver=149.112.112.112 " > /etc/cmdline.d/05-nets.conf &&


## boot config
sleep 3 && clear &&
echo "level 12" &&
rm -fr /etc/mkinitcpio.conf.d &&
rm /boot/initramfs-linux-hardened* &&
mkdir -p /boot/efi /boot/efi/linux /boot/efi/systemd /boot/efi/rescue /boot/efi/boot /boot/kernel &&
mv /boot/*-ucode.img /boot/vmlinuz-linux-hardened /boot/kernel &&
bootctl --path=/boot install &&
mkinitcpio -P &&



## service activation
sleep 3 && clear &&
echo "level 13" &&
systemctl enable systemd-timesyncd.service &&
systemctl enable tangd.socket &&
systemctl enable apparmor.service &&
systemctl enable sshd &&
systemctl enable update.timer &&
systemctl enable prometheus.service &&
systemctl enable prometheus-node-exporter.service &&
systemctl enable irqbalance &&
systemctl enable tuned &&
systemctl enable tuned-ppd.service &&
systemctl enable nginx &&
systemctl enable systemd-networkd &&
systemctl enable systemd-resolved &&
systemctl enable aide.timer &&
systemctl enable sddm &&
systemctl enable --global gcr-ssh-agent.socket &&
systemctl enable --global hypridle.service &&
systemctl enable --global hyprpolkitagent &&
systemctl enable --global waybar &&
systemctl enable --global pipewire-pulse &&
systemctl enable clevis-luks-askpass.path &&

## bind tang
sleep 3 && clear &&
echo "level 14" &&
echo "Insert proc disk encryption password"
sudo clevis luks bind -d $PHYSICAL_PROC tang '{"url":"http://10.10.1.16:7500"}' &&
echo "Insert data disk encryption password"
sudo clevis luks bind -d $PHYSICAL_DATA tang '{"url":"http://10.10.1.16:7500"}' &&

## finishing
sleep 3 && clear &&
echo "level 15" &&
aide --init &&
mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz